name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t deploy .
    
    # - name: Test application
    #   run: |
    #     docker run --name test-container -d -p 8081:80 deploy
    #     sleep 5
    #     curl http://localhost:8080 | grep "Hello, CI/CD!"
    #     docker stop test-container
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub
      run: |
        docker tag deploy ${{ secrets.DOCKER_USERNAME }}/deploy:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/deploy:latest
